FROM golang:1.26.1-alpine

ENV GOCACHE=/workspace/.go-build-cache \
    GOMODCACHE=/workspace/.go-mod-cache \
    HOME=/workspace

RUN adduser -D -s /bin/false judge && \
    mkdir -p /workspace && \
    chown judge:judge /workspace

WORKDIR /workspace

USER judge
