FROM node:24-alpine

RUN npm install --global typescript@6.0 @types/node@24.12.0 coffeescript && \
    npm cache clean --force && \
    adduser -D -s /bin/false judge && \
    mkdir -p /workspace && \
    chown judge:judge /workspace

WORKDIR /workspace

USER judge
