FROM arturolang/arturo:mini AS base

FROM debian:bookworm-slim
COPY --from=base /usr/local/bin/arturo /usr/local/bin/arturo
COPY --from=base /usr/local/lib/ /usr/local/lib/
RUN ldconfig && \
    useradd -m -s /bin/false judge && \
    mkdir -p /workspace && chown judge:judge /workspace
WORKDIR /workspace
USER judge
