FROM python:3.10-slim-bookworm

RUN pip install --no-cache-dir umjunsik==2.0.2 && \
    useradd -m -s /bin/false judge && \
    mkdir -p /workspace && chown judge:judge /workspace

WORKDIR /workspace
USER judge
