FROM alpine:edge
RUN apk add --no-cache --repository=https://dl-cdn.alpinelinux.org/alpine/edge/testing hare && \
    adduser -D -s /bin/false judge && \
    mkdir -p /workspace && chown judge:judge /workspace
WORKDIR /workspace
USER judge
